import {GoogleAuth} from 'google-auth-library';
const SHEET_ID='1tL1u65uuALC6Xky0CbUbPkSX7pZd_twl2Wpy0AYg8eU';
const clean=v=>String(v??'').trim();
const num=v=>Number(String(v??'0').replace(/[^0-9.-]/g,''))||0;
function iso(v){const s=clean(v);if(!s)return'';const m=s.match(/(20\d{2})[^0-9]?(\d{1,2})[^0-9]?(\d{1,2})/);if(m)return`${m[1]}-${m[2].padStart(2,'0')}-${m[3].padStart(2,'0')}`;const md=s.match(/^(\d{1,2})[./-]?(\d{1,2})$/);if(md)return`2026-${md[1].padStart(2,'0')}-${md[2].padStart(2,'0')}`;return s;}
async function sheet(token,name,range){const r=encodeURIComponent(`'${name}'!${range}`);const res=await fetch(`https://sheets.googleapis.com/v4/spreadsheets/${SHEET_ID}/values/${r}`,{headers:{Authorization:`Bearer ${token}`},cache:'no-store'});if(!res.ok)throw new Error(`${name}: Google Sheets ${res.status}`);return (await res.json()).values||[];}
export async function GET(){try{const raw=process.env.GOOGLE_SERVICE_ACCOUNT_JSON;if(!raw)return Response.json({error:'Google 서비스 계정 환경변수가 없습니다.'},{status:500});const auth=new GoogleAuth({credentials:JSON.parse(raw),scopes:['https://www.googleapis.com/auth/spreadsheets.readonly']});const client=await auth.getClient();const t=await client.getAccessToken(),token=t.token||t;const [ov,cv]=await Promise.all([sheet(token,'에이블리 주문','A1:AI2000'),sheet(token,'취소 반품','A1:AQ2000')]);
const orders=[];for(let i=1;i<ov.length;i++){const r=ov[i]||[];const productOrder=clean(r[9]);const product=clean(r[12]);if(!productOrder&&!product)continue;orders.push({date:iso(r[8]||r[5]),productOrder,orderNo:clean(r[10]||r[4]),product,qty:num(r[16])||1,paid:num(r[20]||r[14]||r[13]),status:clean(r[31])});}
const cancels=[];for(let i=1;i<cv.length;i++){const r=cv[i]||[];const reason=clean(r[1]),g=clean(r[6]),productOrder=clean(r[17]),product=clean(r[20]);const returnFields=[r[2],r[3],r[4],r[5]].some(v=>clean(v)&&clean(v)!=='-');const explicitReturn=clean(r[12]).includes('반품');const cancellation=reason.includes('취소')||clean(r[13]).includes('취소')||clean(r[40]).includes('취소');if(!returnFields&&!explicitReturn&&!cancellation)continue;let type='before';if(returnFields||explicitReturn)type='return';else if(g&&g!=='-'&&g!=='취소')type='after';cancels.push({date:iso(r[16]||r[0]),productOrder,orderNo:clean(r[18]),product,paid:num(r[27]||r[21]),reason,type});}
return Response.json({orders,cancels,updatedAt:new Date().toISOString()},{headers:{'Cache-Control':'no-store'}});}catch(e){console.error(e);return Response.json({error:e.message||'대시보드 데이터를 불러오지 못했습니다.'},{status:500});}}
