import {GoogleAuth} from 'google-auth-library';
const SHEET_ID='1tL1u65uuALC6Xky0CbUbPkSX7pZd_twl2Wpy0AYg8eU';
const clean=v=>String(v??'').trim(),num=v=>Number(clean(v).replace(/[^0-9.-]/g,''))||0;
const iso=v=>{const s=clean(v),m=s.match(/(20\d{2})-(\d{1,2})-(\d{1,2})/);if(m)return`${m[1]}-${m[2].padStart(2,'0')}-${m[3].padStart(2,'0')}`;const n=s.replace(/[^0-9]/g,'');if(n.length===6&&/^2\d/.test(n))return`20${n.slice(0,2)}-${n.slice(2,4)}-${n.slice(4,6)}`;if(n.length===8&&/^20/.test(n))return`${n.slice(0,4)}-${n.slice(4,6)}-${n.slice(6,8)}`;return''};
async function sheet(token,name,range){const q=encodeURIComponent(`'${name}'!${range}`),r=await fetch(`https://sheets.googleapis.com/v4/spreadsheets/${SHEET_ID}/values/${q}`,{headers:{Authorization:`Bearer ${token}`},cache:'no-store'});if(!r.ok)throw new Error(`${name}: Google Sheets ${r.status}`);return(await r.json()).values||[]}
export async function GET(){try{const raw=process.env.GOOGLE_SERVICE_ACCOUNT_JSON;if(!raw)throw new Error('Google 서비스 계정 환경변수가 없습니다.');const auth=new GoogleAuth({credentials:JSON.parse(raw),scopes:['https://www.googleapis.com/auth/spreadsheets.readonly']}),client=await auth.getClient(),t=await client.getAccessToken(),token=t.token||t,[ov,cv,iv,mv]=await Promise.all([sheet(token,'에이블리 주문','A1:AI3000'),sheet(token,'취소 반품','A1:AQ3000'),sheet(token,'재고 현황','A1:E3000'),sheet(token,'MD','A1:Z3000')]);
const h=ov[0]||[],idx=n=>h.indexOf(n),I={date:idx('결제일'),po:idx('상품주문번호'),order:idx('주문번호'),productNo:idx('상품번호'),product:idx('상품명'),qty:idx('수량'),sale:idx('판매가'),paid:idx('결제액'),status:idx('주문상태')};const orders=[];const byPo=new Map();for(let i=1;i<ov.length;i++){const r=ov[i]||[],po=clean(r[I.po]),product=clean(r[I.product]),date=iso(r[I.date]);if(!po&&!product&&!date)continue;const qty=num(r[I.qty])||1,salePrice=num(r[I.sale]),o={row:i+1,date,productOrder:po,orderNo:clean(r[I.order]),productNo:clean(r[I.productNo]),product,qty,salePrice,paid:num(r[I.paid]),sales:salePrice,status:clean(r[I.status])};orders.push(o);if(po&&!byPo.has(po))byPo.set(po,o)}
const ids=new Set(byPo.keys()),seen=new Map();for(let i=1;i<cv.length;i++){const r=cv[i]||[],reason=clean(r[1]),returnFields=[r[2],r[3],r[4],r[5]].some(v=>clean(v)&&clean(v)!=='-'),explicitReturn=r.some(v=>clean(v)==='반품'),cancelSignal=reason.includes('취소')||r.some(v=>clean(v).includes('구매자취소')||clean(v).includes('고객 취소')||clean(v).includes('배송지연'));if(!returnFields&&!explicitReturn&&!cancelSignal)continue;const po=r.map(clean).find(v=>ids.has(v));if(!po)continue;const o=byPo.get(po);let type='before',g=clean(r[6]);if(returnFields||explicitReturn)type='return';else if(g&&g!=='-'&&g!=='취소')type='after';const cancelSalePrice=num(r[19])||o.salePrice;const rank={before:1,after:2,return:3};const old=seen.get(po);if(!old||rank[type]>rank[old.type])seen.set(po,{...o,salePrice:cancelSalePrice,sales:cancelSalePrice,reason:reason||'취소',type})}const cancels=[...seen.values()];
const inventory=[];let lastProductNo='',lastProduct='',lastColor='';for(let i=1;i<iv.length;i++){const r=iv[i]||[];if(clean(r[0]))lastProductNo=clean(r[0]);if(clean(r[1]))lastProduct=clean(r[1]);if(clean(r[2]))lastColor=clean(r[2]);const size=clean(r[3]),qty=num(r[4]);if(!lastProductNo||(!size&&!clean(r[4])))continue;inventory.push({productNo:lastProductNo,product:lastProduct,color:lastColor,size,qty,row:i+1})}
const mdUploads=[];for(let i=0;i<mv.length;i++){const r=mv[i]||[];for(let c=0;c<r.length;c++){if(clean(r[c])!=='업로드날짜')continue;let date='';for(let rr=i+1;rr<Math.min(i+4,mv.length)&&!date;rr++)date=iso((mv[rr]||[])[c]);if(!date)continue;let product='';for(let rr=i;rr<Math.min(i+8,mv.length)&&!product;rr++){const row=mv[rr]||[],pc=row.findIndex(x=>clean(x)==='상품명');if(pc>=0){for(let r2=rr+1;r2<Math.min(rr+3,mv.length)&&!product;r2++){const nr=mv[r2]||[];product=clean(nr[pc])||clean(nr[pc+1])}}}mdUploads.push({date,product,row:i+1});break}}
return Response.json({orders,cancels,inventory,mdUploads,updatedAt:new Date().toISOString()},{headers:{'Cache-Control':'no-store'}})}catch(e){console.error(e);return Response.json({error:e.message||'대시보드 데이터를 불러오지 못했습니다.'},{status:500})}}
