import {GoogleAuth} from 'google-auth-library';
const SHEET_ID='1tL1u65uuALC6Xky0CbUbPkSX7pZd_twl2Wpy0AYg8eU';
const clean=v=>String(v??'').trim(),num=v=>Number(clean(v).replace(/[^0-9.-]/g,''))||0;
const iso=v=>{const s=clean(v),m=s.match(/(20\d{2})-(\d{1,2})-(\d{1,2})/);if(m)return`${m[1]}-${m[2].padStart(2,'0')}-${m[3].padStart(2,'0')}`;const n=s.replace(/[^0-9]/g,'');if(n.length===6&&/^2\d/.test(n))return`20${n.slice(0,2)}-${n.slice(2,4)}-${n.slice(4,6)}`;if(n.length===8&&/^20/.test(n))return`${n.slice(0,4)}-${n.slice(4,6)}-${n.slice(6,8)}`;return''};
async function sheet(token,name,range){const q=encodeURIComponent(`'${name}'!${range}`),r=await fetch(`https://sheets.googleapis.com/v4/spreadsheets/${SHEET_ID}/values/${q}`,{headers:{Authorization:`Bearer ${token}`},cache:'no-store'});if(!r.ok)throw new Error(`${name}: Google Sheets ${r.status}`);return(await r.json()).values||[]}
const aliases={date:['업로드날짜','업로드 날짜'],product:['상품명'],md:['md','MD'],taobaoLink:['타오바오/vvic 링크','타오바오 링크','vvic 링크'],cost:['타오바오 가격','도매가','원가'],market:['신상 마켓','신상마켓'],marketPrice:['신상 마켓 가격','신상마켓 가격'],size:['사이즈','size'],color:['색상','컬러','color'],salePrice:['판매 가격','판매가격'],margin:['판매 마진','판매마진'],discountPrice:['할인 가격','할인가격'],discountMargin:['할인 가격 마진','할인가격마진']};
function mdRows(mv){let best=null;for(let i=0;i<Math.min(20,mv.length);i++){const row=(mv[i]||[]).map(clean),score=Object.values(aliases).filter(names=>names.some(n=>row.includes(n))).length;if(!best||score>best.score)best={i,row,score}}if(!best||best.score<2)return[];const pos={};for(const[k,names]of Object.entries(aliases))pos[k]=best.row.findIndex(v=>names.includes(v));const out=[];for(let i=best.i+1;i<mv.length;i++){const r=mv[i]||[],get=k=>pos[k]>=0?clean(r[pos[k]]):'',date=iso(get('date')),product=get('product');if(!date&&!product)continue;out.push({date,product,md:get('md'),taobaoLink:get('taobaoLink'),cost:num(get('cost')),market:get('market'),marketPrice:num(get('marketPrice')),size:get('size'),color:get('color'),salePrice:num(get('salePrice')),margin:num(get('margin')),discountPrice:num(get('discountPrice')),discountMargin:num(get('discountMargin')),row:i+1})}return out}
export async function GET(){try{const raw=process.env.GOOGLE_SERVICE_ACCOUNT_JSON;if(!raw)throw new Error('Google 서비스 계정 환경변수가 없습니다.');const auth=new GoogleAuth({credentials:JSON.parse(raw),scopes:['https://www.googleapis.com/auth/spreadsheets.readonly']}),client=await auth.getClient(),t=await client.getAccessToken(),token=t.token||t,[ov,cv,iv,mv]=await Promise.all([sheet(token,'에이블리 주문','A1:AI3000'),sheet(token,'취소 반품','A1:AQ3000'),sheet(token,'재고 현황','A1:E3000'),sheet(token,'MD','A1:Z3000')]);
const h=ov[0]||[],idx=n=>h.indexOf(n),I={date:idx('결제일'),po:idx('상품주문번호'),order:idx('주문번호'),productNo:idx('상품번호'),product:idx('상품명'),qty:idx('수량'),sale:idx('판매가'),paid:idx('결제액'),status:idx('주문상태')};const orders=[];const byPo=new Map();for(let i=1;i<ov.length;i++){const r=ov[i]||[],po=clean(r[I.po]),product=clean(r[I.product]),date=iso(r[I.date]);if(!po&&!product&&!date)continue;const qty=num(r[I.qty])||1,salePrice=num(r[I.sale]),o={row:i+1,date,productOrder:po,orderNo:clean(r[I.order]),productNo:clean(r[I.productNo]),product,qty,salePrice,paid:num(r[I.paid]),sales:salePrice,status:clean(r[I.status])};orders.push(o);if(po&&!byPo.has(po))byPo.set(po,o)}
const ids=new Set(byPo.keys()),seen=new Map();for(let i=1;i<cv.length;i++){const r=cv[i]||[],reason=clean(r[1]),returnFields=[r[2],r[3],r[4],r[5]].some(v=>clean(v)&&clean(v)!=='-'),explicitReturn=r.some(v=>clean(v)==='반품'),cancelSignal=reason.includes('취소')||r.some(v=>clean(v).includes('구매자취소')||clean(v).includes('고객 취소')||clean(v).includes('배송지연'));if(!returnFields&&!explicitReturn&&!cancelSignal)continue;const po=r.map(clean).find(v=>ids.has(v));if(!po)continue;const o=byPo.get(po);let type='before',g=clean(r[6]);if(returnFields||explicitReturn)type='return';else if(g&&g!=='-'&&g!=='취소')type='after';const cancelSalePrice=num(r[19])||o.salePrice;const rank={before:1,after:2,return:3};const old=seen.get(po);if(!old||rank[type]>rank[old.type])seen.set(po,{...o,salePrice:cancelSalePrice,sales:cancelSalePrice,reason:reason||'취소',type})}const cancels=[...seen.values()];
const inventory=[];let lastProductNo='',lastProduct='',lastColor='';for(let i=1;i<iv.length;i++){const r=iv[i]||[];if(clean(r[0]))lastProductNo=clean(r[0]);if(clean(r[1]))lastProduct=clean(r[1]);if(clean(r[2]))lastColor=clean(r[2]);const size=clean(r[3]),qty=num(r[4]);if(!lastProductNo||(!size&&!clean(r[4])))continue;inventory.push({productNo:lastProductNo,product:lastProduct,color:lastColor,size,qty,row:i+1})}
const mdProducts=mdRows(mv),mdUploads=mdProducts.filter(x=>x.date).map(x=>({date:x.date,product:x.product,md:x.md,cost:x.cost,market:x.market,marketPrice:x.marketPrice,size:x.size,color:x.color,salePrice:x.salePrice,margin:x.margin,discountPrice:x.discountPrice,discountMargin:x.discountMargin,row:x.row}));
return Response.json({orders,cancels,inventory,mdUploads,mdProducts,updatedAt:new Date().toISOString()},{headers:{'Cache-Control':'no-store'}})}catch(e){console.error(e);return Response.json({error:e.message||'대시보드 데이터를 불러오지 못했습니다.'},{status:500})}}
