'use client';
import{useState}from'react';import*as XLSX from'xlsx';
const text=v=>String(v??'').trim(),digits=v=>text(v).replace(/\D/g,''),phone=v=>digits(v).replace(/^(01\d)(\d{3,4})(\d{4})$/,'$1-$2-$3');
const DEFAULT_TEMPLATE=`안녕하세요 {수취인명} 고객님

고객님께서 주문하신 {상품명} 상품은 저희 주문량이 밀려 저희 업체로 공급되는 시간이 지체되어 곧바로 배송이 어려워 안내드립니다. 

배송 기간은 영업일 기준으로 3일~7일 정도 소요될 수도 있는 것으로 확인됩니다. 배송현황은 CJ대한통운으로 등록되어있을텐데 실제 배송은 우체국택배로 진행됩니다!

문자 확인 후 답변 해주시면 배송 진행, 혹은 취소 진행으로 도와드리겠습니다

감사합니다!!`;
const POST_HEADERS=['받는 분 이름','받는 분 우편번호','받는 분 주소(도로명주소+건물번호, 읍/면/동까지)','받는분 상세주소(나머지주소\n / 상세주소가 없는 경우 입력 예시 : . , 등)','받는 분 연락처','물품중량(kg)','물품크기(cm)\n크기=가로+세로+높이','분할접수여부','첫번째 중량(kg)','첫번째 크기(cm)','두번째 중량(kg)','두번째 크기(cm)','내용품코드','내용물','배달방식','배송시특이사항','보내는분 이름','보내는분 우편번호','보내는분 주소(도로명주소+건물번호, 읍/면/동까지)','보내는분 상세주소(나머지주소)','보내는분 연락처'],FIXED_BEFORE_MEMO=['5','80','N','11','80','11','80','[25]의류/패션잡화','의류','비대면'],FIXED_SENDER=['오어즈','48224','부산광역시 수영구 망미번영로74번길 43-4','수정 1층 102호','010-5943-7724'];
function splitAddress(v){const s=text(v).replace(/\s+/g,' '),m=s.match(/^(.+?(?:로|길)\s*\d+(?:-\d+)?)(?:\s+(.*))?$/);return m?[m[1],m[2]||'.']:[s,'.'];}
function parsePostRows(a){if(!a?.length)return[];const o=[];for(let i=1;i<a.length;i++){const r=a[i]||[];if(text(r[7])!=='우체국 배송'||text(r[31]).includes('취소'))continue;const full=text(r[29]),name=text(r[26]);if(!name||!full)continue;const[address,detail]=splitAddress(full);o.push({id:`${i+1}-${text(r[9])}`,rowNumber:i+1,orderNo:text(r[10]||r[4]),productOrderNo:text(r[9]),name,phone:phone(r[27]),zip:text(r[28]),address,detail,memo:text(r[30])});}return o;}
function parsePostSheet(w){const s=w.Sheets['에이블리 주문']||w.Sheets[w.SheetNames[0]];return parsePostRows(XLSX.utils.sheet_to_json(s,{header:1,defval:'',raw:false}));}
function parseSmsSheet(w){const s=w.Sheets[w.SheetNames[0]],a=XLSX.utils.sheet_to_json(s,{defval:''});return a.filter(r=>text(r['상품주문번호']||r['주문번호']||r['상품명'])).map((r,i)=>({id:text(r['상품주문번호'])||`${text(r['주문번호'])}-${i}`,name:text(r['수취인명']||r['주문자명']),phone:phone(r['수취인 연락처']||r['연락처']),product:text(r['상품명']),option:text(r['옵션 정보']),qty:text(r['수량'])||'1'}));}
function normalize(s){return text(s).replace(/[\s,().-]/g,'').toLowerCase();}
function parsePostalPaste(raw){const lines=raw.split(/\r?\n/).map(x=>x.trim()).filter(Boolean),out=[];for(let i=0;i<lines.length;i++){const tracking=(lines[i].match(/\b\d{13}\b/)||[])[0];if(!tracking)continue;let block=lines[i];if(i+1<lines.length&&!/\b\d{13}\b/.test(lines[i+1]))block+=' '+lines[i+1];out.push({id:`${tracking}-${i}`,tracking,line:block});}return out;}
function matchTracking(pasted,orders){return pasted.map(p=>{let cand=orders.filter(o=>normalize(p.line).includes(normalize(o.name)));if(cand.length>1)cand=cand.filter(o=>normalize(p.line).includes(normalize(o.zip))||normalize(p.line).includes(normalize(o.address).slice(0,10)));return{...p,match:cand.length===1?cand[0]:null,status:cand.length===1?'자동매칭':cand.length?'확인 필요':'매칭 실패'};});}
export default function Page(){const[mode,setMode]=useState('sms'),[rows,setRows]=useState([]),[postRows,setPostRows]=useState([]),[notice,setNotice]=useState(''),[template,setTemplate]=useState(DEFAULT_TEMPLATE),[googleLoading,setGoogleLoading]=useState(false),[paste,setPaste]=useState(''),[matches,setMatches]=useState([]),[writeNotice,setWriteNotice]=useState(''),[ablyWb,setAblyWb]=useState(null),[ablyFileName,setAblyFileName]=useState('');
async function loadFile(e,type){const f=e.target.files?.[0];if(!f)return;try{const w=XLSX.read(await f.arrayBuffer(),{type:'array'}),p=type==='post'?parsePostSheet(w):parseSmsSheet(w);type==='post'?setPostRows(p):setRows(p);setNotice(type==='post'?`우체국 배송 ${p.length}건을 찾았습니다.`:`${p.length}건을 불러왔습니다.`);}catch{setNotice('엑셀을 읽지 못했습니다.');}}
async function loadAblyFile(e){const f=e.target.files?.[0];if(!f)return;try{const w=XLSX.read(await f.arrayBuffer(),{type:'array',cellStyles:true});const target=w.SheetNames.find(n=>n.includes('배송 중 관리'))||w.SheetNames.find(n=>{const a=XLSX.utils.sheet_to_json(w.Sheets[n],{header:1,defval:''});return a[0]?.includes('상품주문번호')&&a[0]?.includes('택배사 코드')&&a[0]?.includes('송장번호');});if(!target)throw new Error();setAblyWb(w);setAblyFileName(f.name);setWriteNotice(`에이블리 배송 중 관리 엑셀을 불러왔습니다: ${f.name}`);}catch{setAblyWb(null);setAblyFileName('');setWriteNotice('에이블리 배송 중 관리 엑셀을 읽지 못했습니다.');}}
async function loadGoogle(){setGoogleLoading(true);setNotice('Google 주문시트를 불러오는 중...');try{const r=await fetch('/api/google-orders',{cache:'no-store'}),d=await r.json();if(!r.ok)throw new Error(d.error);setPostRows(d.rows||[]);setNotice(`Google 주문시트에서 우체국 배송 ${(d.rows||[]).length}건을 찾았습니다.`);}catch(e){setNotice(`연결 실패: ${e.message}`);}finally{setGoogleLoading(false);}}
function message(r){return template.replaceAll('{수취인명}',r.name||'고객').replaceAll('{상품명}',r.product||'주문 상품').replaceAll('{옵션}',r.option||'').replaceAll('{수량}',r.qty||'1');}async function copy(r){await navigator.clipboard.writeText(message(r));}
function downloadPost(){const top=['받는 분 정보','','','','','물품정보(*필수)','','','','','','','','','','','보내는 분 정보(*선택)','','','',''],data=postRows.map(r=>[r.name,r.zip,r.address,r.detail||'.',r.phone,...FIXED_BEFORE_MEMO,r.memo||'',...FIXED_SENDER]),s=XLSX.utils.aoa_to_sheet([top,POST_HEADERS,...data]);s['!merges']=[XLSX.utils.decode_range('A1:E1'),XLSX.utils.decode_range('F1:P1'),XLSX.utils.decode_range('Q1:U1')];const w=XLSX.utils.book_new();XLSX.utils.book_append_sheet(w,s,'방문접수소포 파일접수양식');XLSX.writeFile(w,`우체국_등록용_${new Date().toISOString().slice(0,10)}.xlsx`);}
function runMatch(){const p=parsePostalPaste(paste);setMatches(matchTracking(p,postRows));setWriteNotice(`${p.length}개의 확정 등기번호를 읽었습니다.`);}
async function writeGoogle(){const ok=matches.filter(x=>x.match).map(x=>({rowNumber:x.match.rowNumber,tracking:x.tracking}));if(!ok.length)return;const r=await fetch('/api/tracking',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({updates:ok})}),d=await r.json();setWriteNotice(r.ok?`주문시트 택배사(G열) 우체국 / 배송관리(H열) 송장번호 ${d.count}건 변경 완료`:(d.error||'기입 실패'));}
function downloadAbly(){if(!ablyWb){setWriteNotice('먼저 에이블리 배송 중 관리 엑셀을 올려주세요.');return;}const ok=matches.filter(x=>x.match);if(!ok.length)return;const target=ablyWb.SheetNames.find(n=>n.includes('배송 중 관리'))||ablyWb.SheetNames.find(n=>{const a=XLSX.utils.sheet_to_json(ablyWb.Sheets[n],{header:1,defval:''});return a[0]?.includes('상품주문번호');});const ws=ablyWb.Sheets[target],a=XLSX.utils.sheet_to_json(ws,{header:1,defval:'',raw:false});const h=a[0]||[],pi=h.indexOf('상품주문번호'),oi=h.indexOf('주문번호'),ci=h.indexOf('택배사'),cci=h.indexOf('택배사 코드'),ti=h.indexOf('송장번호');let changed=0;for(const x of ok){const m=x.match;for(let i=1;i<a.length;i++){const productMatch=pi>=0&&text(a[i][pi])===text(m.productOrderNo);const orderMatch=oi>=0&&text(a[i][oi])===text(m.orderNo);if(productMatch||(!m.productOrderNo&&orderMatch)){if(ci>=0)a[i][ci]='우체국택배';if(cci>=0)a[i][cci]=2;if(ti>=0)a[i][ti]=x.tracking;changed++;}}}if(!changed){setWriteNotice('업로드한 에이블리 엑셀에서 매칭되는 상품주문번호를 찾지 못했습니다.');return;}const newWs=XLSX.utils.aoa_to_sheet(a);for(const k of ['!cols','!rows','!merges'])if(ws[k])newWs[k]=ws[k];ablyWb.Sheets[target]=newWs;const base=(ablyFileName||'에이블리_배송 중 관리.xlsx').replace(/\.xlsx?$/i,'');XLSX.writeFile(ablyWb,`${base}_우체국송장수정.xlsx`);setWriteNotice(`에이블리 원본 엑셀에서 ${changed}건의 택배사·택배사코드·송장번호만 변경했습니다.`);}
return <main className="wrap"><h1>Ably Manager</h1><p className="sub">문자 · 우체국 발송 · 송장 매칭을 한 곳에서 처리해요.</p><div className="actions" style={{marginBottom:18}}><button onClick={()=>setMode('sms')}>문자 도우미</button><button onClick={()=>setMode('post')}>우체국 엑셀 만들기</button><button onClick={()=>setMode('tracking')}>송장 매칭</button></div>{mode==='sms'?<><section className="card"><h2>에이블리 엑셀 올리기</h2><input type="file" accept=".xlsx,.xls" onChange={e=>loadFile(e,'sms')}/></section><section className="card"><h2>문자 양식</h2><textarea value={template} onChange={e=>setTemplate(e.target.value)} style={{width:'100%',minHeight:300}}/></section>{rows.map(r=><article className="card" key={r.id}><b>{r.name} · {r.phone}</b><div className="msg">{message(r)}</div><div className="actions"><button onClick={()=>copy(r)}>문자 복사</button>{r.phone&&<button onClick={()=>navigator.clipboard.writeText(r.phone)}>번호 복사</button>}</div></article>)}</>:mode==='post'?<><section className="card"><h2>발송 주문 불러오기</h2><button onClick={loadGoogle} disabled={googleLoading}>{googleLoading?'불러오는 중...':'Google 주문시트 불러오기'}</button><p>{notice}</p><input type="file" accept=".xlsx,.xls" onChange={e=>loadFile(e,'post')}/></section><div className="row"><h2>발송 대상</h2><b>{postRows.length}건</b></div>{postRows.length>0&&<button onClick={downloadPost}>우체국 등록용 엑셀 다운로드</button>}{postRows.map(r=><article className="card" key={r.id}><b>{r.name} · {r.phone}</b><p>{r.zip} · {r.address} {r.detail}</p>{r.memo&&<p>배송 메모: {r.memo}</p>}</article>)}</>:<><section className="card"><h2>1. Google 주문시트 불러오기</h2><button onClick={loadGoogle} disabled={googleLoading}>{googleLoading?'불러오는 중...':'우체국 배송 주문 불러오기'}</button><p>{notice}</p></section><section className="card"><h2>2. 우체국 신청내역 붙여넣기</h2><p className="sub">우체국 방문접수소포 신청내역을 그대로 복사해 붙여넣으세요.</p><textarea value={paste} onChange={e=>setPaste(e.target.value)} placeholder="우체국 신청내역을 여기에 붙여넣기" style={{width:'100%',minHeight:220,padding:12}}/><div className="actions"><button onClick={runMatch}>등기번호 자동 매칭</button></div></section><div className="row"><h2>매칭 결과</h2><b>{matches.filter(x=>x.match).length}/{matches.length}건</b></div>{matches.map(x=><article className="card" key={x.id}><div className="row"><b>{x.match?.name||'확인 필요'}</b><span>{x.status}</span></div><p>등기번호 {x.tracking}</p>{x.match&&<p className="sub">주문번호 {x.match.orderNo}</p>}</article>)}{matches.some(x=>x.match)&&<section className="card"><h2>3. 에이블리 배송 중 관리 엑셀 올리기</h2><p className="sub">에이블리에서 받은 원본 엑셀을 올리면 기존 정보와 발송 처리일은 그대로 두고 택배사·택배사 코드·송장번호만 변경합니다.</p><input type="file" accept=".xlsx,.xls" onChange={loadAblyFile}/>{ablyFileName&&<p>{ablyFileName} 불러오기 완료</p>}<h2>4. 처리하기</h2><div className="actions"><button onClick={writeGoogle}>주문시트 송장번호 자동 기입</button><button onClick={downloadAbly} disabled={!ablyWb}>에이블리 원본 엑셀 송장 변경 다운로드</button></div>{writeNotice&&<p>{writeNotice}</p>}</section>}</>}</main>}
