'use client';
import {useEffect} from 'react';
import {usePathname} from 'next/navigation';
const descriptions={
'매출 대시보드':'주문·취소·반품을 기준으로 매출 흐름과 월별 추이를 확인합니다.',
'오늘의 MD':'최근 주문과 신상품 등록 데이터를 요약해 지금 확인할 핵심 변화를 보여줍니다.',
'상품별 판매분석':'상품별 주문·취소·반품·재고 데이터를 자세히 확인합니다.',
'상품 반응':'최근 반응 상승·지속·둔화 등 상품별 움직임을 모아서 확인합니다.',
'문자 도우미':'주문 엑셀을 불러와 배송지연 안내 문자를 빠르게 만들고 복사합니다.',
'우체국 엑셀 만들기':'Google 주문시트의 발송 대상을 읽어 우체국 접수용 엑셀을 만듭니다.',
'송장 매칭':'우체국 송장번호를 주문과 매칭하고 에이블리 등록용 파일을 만듭니다.',
'상품번호 매칭':'에이블리 상품목록과 MD 시트를 비교해 상품번호를 안전하게 자동 입력합니다.'};
export default function TodayHomeNav(){const path=usePathname();useEffect(()=>{if(path!=='/')return;const main=document.querySelector('main.wrap'),nav=main?.querySelector('.actions');if(!main||!nav)return;const buttons=[...nav.querySelectorAll('button')];const product=buttons.find(b=>b.textContent?.includes('상품별 판매분석')||b.textContent?.trim()==='상품 분석'||b.textContent?.trim()==='오늘의 MD');if(product){product.textContent='상품별 판매분석';product.onclick=()=>{location.href='/products'}}let today=nav.querySelector('[data-today-md]');if(!today){today=document.createElement('button');today.dataset.todayMd='true';today.textContent='오늘의 MD';today.onclick=()=>{location.href='/today'};product?.before(today)}let reaction=nav.querySelector('[data-product-reaction]');if(!reaction){reaction=document.createElement('button');reaction.dataset.productReaction='true';reaction.textContent='상품 반응';reaction.onclick=()=>{location.href='/product-reaction'};product?.after(reaction)}let match=nav.querySelector('[data-product-match]');if(!match){match=document.createElement('button');match.dataset.productMatch='true';match.textContent='상품번호 매칭';match.onclick=()=>{location.href='/product-match'};nav.appendChild(match)}const dashboard=[...nav.querySelectorAll('button')].find(b=>b.textContent?.trim()==='매출 대시보드');if(dashboard)dashboard.onclick=()=>{location.href='/dashboard'};const oldAsk=nav.querySelector('[data-oars-ask]');if(oldAsk)oldAsk.remove();
const all=[...nav.querySelectorAll('button')];const toolNames=new Set(['문자 도우미','우체국 엑셀 만들기','송장 매칭']);for(const b of all){const name=b.textContent?.trim();if(toolNames.has(name)){const original=b.onclick;b.onclick=e=>{[...main.children].forEach(el=>{if(el!==nav&&el.tagName!=='H1'&&!(el.tagName==='P'&&el.classList.contains('sub'))&&el.dataset?.homeIntro!=='true')el.style.display='';});const intro=main.querySelector('[data-home-intro]');if(intro)intro.style.display='none';original?.call(b,e)}}
[...main.children].forEach(el=>{if(el!==nav&&el.tagName!=='H1'&&!(el.tagName==='P'&&el.classList.contains('sub')))el.style.display='none'});let intro=main.querySelector('[data-home-intro]');if(!intro){intro=document.createElement('section');intro.dataset.homeIntro='true';intro.style.cssText='display:grid;grid-template-columns:repeat(auto-fit,minmax(260px,1fr));gap:12px;margin-top:22px';all.forEach(b=>{const name=b.textContent?.trim();if(!name)return;const card=document.createElement('div');card.style.cssText='border:1px solid #34383a;border-radius:14px;padding:18px;background:#171a1b';const title=document.createElement('strong');title.textContent=name;title.style.cssText='display:block;font-size:17px;margin-bottom:8px';const desc=document.createElement('div');desc.textContent=descriptions[name]||'';desc.style.cssText='font-size:14px;line-height:1.55;color:#aaa';card.append(title,desc);card.onclick=()=>b.click();card.style.cursor='pointer';intro.appendChild(card)});nav.after(intro)}},[path]);return null;}
