import {GoogleAuth} from 'google-auth-library';
const SHEET_ID='1tL1u65uuALC6Xky0CbUbPkSX7pZd_twl2Wpy0AYg8eU';
const clean=v=>String(v??'').trim();
const norm=s=>clean(s).toLowerCase().replace(/\[[^\]]*\]|\([^)]*\)/g,' ').replace(/\b\d+\s*colou?r\b/gi,' ').replace(/[^0-9a-z가-힣]+/g,'');
const tokens=s=>new Set(clean(s).toLowerCase().replace(/\[[^\]]*\]|\([^)]*\)/g,' ').replace(/[^0-9a-z가-힣]+/g,' ').split(/\s+/).filter(x=>x.length>1));
const sim=(a,b)=>{const A=tokens(a),B=tokens(b);if(!A.size||!B.size)return 0;let hit=0;for(const x of A)if(B.has(x))hit++;return hit/Math.max(A.size,B.size)};
async function values(token){const q=encodeURIComponent("'MD'!A1:Z3000"),r=await fetch(`https://sheets.googleapis.com/v4/spreadsheets/${SHEET_ID}/values/${q}`,{headers:{Authorization:`Bearer ${token}`},cache:'no-store'});if(!r.ok)throw new Error(`MD 시트 읽기 실패 (${r.status})`);return(await r.json()).values||[]}
function blocks(a){const out=[];for(let r=0;r<a.length;r++){const row=a[r]||[];for(let c=0;c<row.length;c++){if(clean(row[c])!=='상품번호')continue;let product='',productRow=-1,date='';for(let rr=r;rr<Math.min(a.length,r+9);rr++){const x=a[rr]||[];for(let cc=0;cc<x.length;cc++){const label=clean(x[cc]);if(label==='상품명'&&!product){product=clean((a[rr+1]||[])[cc])||clean(x[cc+1]);productRow=rr+1}if(label==='업로드날짜'&&!date)date=clean((a[rr+1]||[])[cc])||clean(x[cc+1]);}}if(product)out.push({headerRow:r+1,valueRow:r+2,col:c+1,product,productRow:productRow+1,date,existing:clean((a[r+1]||[])[c])});}}
return out}
function pick(block,goods){const n=norm(block.product),exact=goods.filter(g=>norm(g.name)===n);if(exact.length===1)return{g:exact[0],status:'자동매칭',score:1};const scored=goods.map(g=>({g,score:sim(block.product,g.name)})).sort((a,b)=>b.score-a.score);const best=scored[0],second=scored[1];if(best&&best.score>=.8&&best.score-(second?.score||0)>=.15)return{...best,status:'유사명 자동매칭'};return{g:null,status:'확인 필요',score:best?.score||0,candidate:best?.g?.name||''}}
export async function POST(req){try{const {goods=[]}=await req.json();if(!Array.isArray(goods)||!goods.length)return Response.json({error:'에이블리 상품목록 데이터가 없습니다.'},{status:400});const unique=[...new Map(goods.filter(x=>clean(x.productNo)&&clean(x.name)).map(x=>[clean(x.productNo),{productNo:clean(x.productNo),name:clean(x.name),category:clean(x.category),registeredAt:clean(x.registeredAt)}])).values()];const raw=process.env.GOOGLE_SERVICE_ACCOUNT_JSON;if(!raw)throw new Error('Google 서비스 계정 환경변수가 없습니다.');const auth=new GoogleAuth({credentials:JSON.parse(raw),scopes:['https://www.googleapis.com/auth/spreadsheets']}),client=await auth.getClient(),t=await client.getAccessToken(),token=t.token||t,a=await values(token),bs=blocks(a),results=[],updates=[];for(const b of bs){if(b.existing){results.push({...b,productNo:b.existing,status:'기존값 유지'});continue}const m=pick(b,unique);if(m.g){results.push({...b,productNo:m.g.productNo,ablyName:m.g.name,category:m.g.category,status:m.status,score:m.score});updates.push({range:`'MD'!${String.fromCharCode(64+b.col)}${b.valueRow}`,values:[[m.g.productNo]]})}else results.push({...b,status:m.status,candidate:m.candidate,score:m.score})}if(updates.length){const r=await fetch(`https://sheets.googleapis.com/v4/spreadsheets/${SHEET_ID}/values:batchUpdate`,{method:'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify({valueInputOption:'RAW',data:updates})});if(!r.ok)throw new Error(`상품번호 쓰기 실패 (${r.status})`)}return Response.json({total:bs.length,written:updates.length,existing:results.filter(x=>x.status==='기존값 유지').length,needsReview:results.filter(x=>x.status==='확인 필요').length,results})}catch(e){console.error(e);return Response.json({error:e.message||'상품번호 매칭 실패'},{status:500})}}
