import {GoogleAuth} from 'google-auth-library';
const SHEET_ID='1tL1u65uuALC6Xky0CbUbPkSX7pZd_twl2Wpy0AYg8eU',SEOUL={latitude:37.5665,longitude:126.9780};
const txt=v=>String(v??'').trim(),num=v=>{const n=Number(txt(v).replace(/[^0-9.-]/g,''));return Number.isFinite(n)?n:0},norm=s=>txt(s).replace(/\s+/g,'').toLowerCase(),fmt=n=>Math.round(n||0).toLocaleString('ko-KR');
const parseDate=v=>{const s=txt(v);let m=s.match(/^(\d{2})(\d{2})(\d{2})$/);if(m)return new Date(2000+ +m[1],+m[2]-1,+m[3]);m=s.match(/^(\d{4})[-./](\d{1,2})[-./](\d{1,2})/);return m?new Date(+m[1],+m[2]-1,+m[3]):null};
async function weather(){try{const u=new URL('https://api.open-meteo.com/v1/forecast');u.searchParams.set('latitude',SEOUL.latitude);u.searchParams.set('longitude',SEOUL.longitude);u.searchParams.set('timezone','Asia/Seoul');u.searchParams.set('current','temperature_2m,apparent_temperature');u.searchParams.set('daily','temperature_2m_max,temperature_2m_min');u.searchParams.set('forecast_days','7');const r=await fetch(u,{cache:'no-store'});return r.ok?await r.json():null}catch{return null}}
async function mdRows(){try{const raw=process.env.GOOGLE_SERVICE_ACCOUNT_JSON;if(!raw)return[];const auth=new GoogleAuth({credentials:JSON.parse(raw),scopes:['https://www.googleapis.com/auth/spreadsheets.readonly']}),client=await auth.getClient(),token=await client.getAccessToken(),r=await fetch(`https://sheets.googleapis.com/v4/spreadsheets/${SHEET_ID}/values/${encodeURIComponent('MD!A1:Z3000')}`,{headers:{Authorization:`Bearer ${token.token||token}`},cache:'no-store'});if(!r.ok)return[];const a=(await r.json()).values||[];let hi=a.findIndex(row=>row.some(c=>norm(c).includes('업로드날짜'))&&row.some(c=>norm(c).includes('상품명')));if(hi<0)hi=0;const h=a[hi]||[],find=(...names)=>h.findIndex(x=>names.some(n=>norm(x).includes(norm(n)))),ix={date:find('업로드날짜'),product:find('상품명'),sale:find('판매가격'),margin:find('판매마진'),discount:find('할인가격'),discountMargin:find('할인가격마진')};return a.slice(hi+1).map(r=>({date:ix.date>=0?txt(r[ix.date]):'',product:ix.product>=0?txt(r[ix.product]):'',sale:ix.sale>=0?num(r[ix.sale]):0,margin:ix.margin>=0?num(r[ix.margin]):0,discount:ix.discount>=0?num(r[ix.discount]):0,discountMargin:ix.discountMargin>=0?num(r[ix.discountMargin]):0})).filter(x=>x.product||x.date)}catch{return[]}}
function category(name){const s=txt(name);for(const[k,words]of[['원피스',['원피스','드레스']],['상의',['가디건','니트','티셔츠','블라우스','셔츠','탑','나시','홀터넥']],['스커트',['스커트','치마']],['팬츠',['팬츠','바지','슬랙스','데님']],['아우터',['자켓','재킷','점퍼','코트','후드집업']],['세트',['세트','셋업']]])if(words.some(w=>s.includes(w)))return k;return'기타'}
const avg=(a,k)=>{const v=a.map(x=>x[k]).filter(x=>x>0);return v.length?v.reduce((s,n)=>s+n,0)/v.length:0},sig=(s,t)=>(s||[]).find(x=>x.title===t)?.products||[],uniq=a=>a.filter((x,i,z)=>z.findIndex(y=>(y.productNo||y.name)===(x.productNo||x.name))===i);
const productLines=a=>a.length?a.slice(0,4).map((x,i)=>`${i+1}. ${x.name}\n   최근 7일 ${x.q7||0}개 · 최근 30일 ${x.q30||0}개${x.stock?` · 재고 ${x.stock}개`:''}`).join('\n'):'현재 조건에 해당하는 상품이 없습니다.';
export async function POST(req){try{const input=await req.json(),m=input.market||{},w=await weather(),all=await mdRows(),now=new Date(),d30=new Date(now);d30.setDate(d30.getDate()-29);const recent=all.filter(x=>{const d=parseDate(x.date);return d&&d>=d30&&d<=now}),cm={};recent.forEach(x=>cm[category(x.product)]=(cm[category(x.product)]||0)+1);const cats=Object.entries(cm).sort((a,b)=>b[1]-a[1]),sale=avg(recent,'sale'),margin=avg(recent,'margin'),hot=uniq([...sig(input.signals,'최근 반응 상승'),...sig(input.signals,'반응 지속'),...sig(input.signals,'신규 반응 감지')]),weak=uniq([...sig(input.signals,'반응 둔화'),...sig(input.signals,'반응 멈춤')]);
const observation=`[주문 흐름]\n• 7일: ${m.p7??'-'} → ${m.q7??'-'}개\n• 14일: ${m.p14??'-'} → ${m.q14??'-'}개\n• 30일: ${m.p30??'-'} → ${m.q30??'-'}개\n• 주문 발생일: 최근 7일 ${m.days7??'-'}일 / 이전 ${m.prevDays7??'-'}일 · 최근 30일 ${m.days30??'-'}일 / 이전 ${m.prevDays30??'-'}일\n\n[MD 업로드]\n• 7일: ${m.mdPrev7??'-'} → ${m.md7??'-'}개\n• 14일: ${m.mdPrev14??'-'} → ${m.md14??'-'}개\n• 30일: ${m.mdPrev30??'-'} → ${m.md30??'-'}개\n• 최근 30일 구성: ${cats.slice(0,4).map(([k,v])=>`${k} ${v}개`).join(' · ')||'분류 데이터 부족'}${sale?`\n• 평균 판매가: 약 ${fmt(sale)}원`:''}${margin?` · 평균 판매마진: 약 ${fmt(margin)}원`:''}\n\n[해석]\n업로드량은 늘었지만 주문 수와 주문 발생일은 함께 줄었습니다. 현재 데이터에서는 단순히 상품을 적게 올려서 주문이 줄었다고 보기 어렵습니다.`;
const direction=`[우선 볼 상품 — 반응 신호]\n${productLines(hot)}\n\n[다음 소싱에서 할 일]\n• 위 상품들의 카테고리·핏·기장·소재·가격대를 MD 시트 신규 후보와 비교합니다.\n• 공통점이 있는 상품은 한꺼번에 많이 늘리지 않고 소규모로 등록해 반응을 비교합니다.\n• 주문 1건은 재고 신호로 보지 않고, 서로 다른 날짜에 주문이 반복될 때 재고 검토로 넘깁니다.\n\n[비중을 줄여 볼 후보 — 둔화/정지]\n${productLines(weak)}`;
const caution=`[확정할 수 없는 것]\n• 현재 시트에는 에이블리 노출수·클릭수·전환율이 없어 주문 감소 원인을 상품 구성 하나로 확정할 수 없습니다.\n\n[다음에 꼭 연결할 데이터]\n• MD 시트에 등록한 신상품 → 실제 주문 발생 여부를 상품번호 기준으로 연결합니다.\n• 그러면 최근 신상품 중 실제 반응이 생긴 비율과 카테고리·가격대별 차이를 따로 볼 수 있습니다.\n\n[판단 기준]\n기존 주력상품과 신상품이 동시에 약하다면 신상품 선택 외에 계절 전환이나 노출 변화 가능성도 남겨둬야 합니다.`;
const cur=w?.current||{},mx=(w?.daily?.temperature_2m_max||[]).slice(0,7),mn=(w?.daily?.temperature_2m_min||[]).slice(0,7),hi=mx.length?Math.max(...mx):null,lo=mn.length?Math.min(...mn):null;const weatherText=`현재 서울 ${cur.temperature_2m??'-'}℃ · 체감 ${cur.apparent_temperature??'-'}℃${hi!=null&&lo!=null?`\n향후 7일 기온 범위 약 ${lo.toFixed(0)}~${hi.toFixed(0)}℃`:''}\n\n날씨는 주문 감소 원인으로 보지 않고, 가을용 긴팔·니트·가디건·레이어드류의 등록 타이밍을 보는 보조 지표로만 사용합니다.`;return Response.json({observation,direction,caution,weather:weatherText,ai:false,source:'rule-based+md-sheet'})}catch(e){return Response.json({error:e.message||'OARS 분석 실패'},{status:500})}}
