import {GoogleAuth} from 'google-auth-library';
const SHEET_ID='1tL1u65uuALC6Xky0CbUbPkSX7pZd_twl2Wpy0AYg8eU',SEOUL={latitude:37.5665,longitude:126.9780};
const txt=v=>String(v??'').trim(),num=v=>{const n=Number(txt(v).replace(/[^0-9.-]/g,''));return Number.isFinite(n)?n:0},norm=s=>txt(s).replace(/\s+/g,'').toLowerCase();
const parseDate=v=>{const s=txt(v);let m=s.match(/^(\d{2})(\d{2})(\d{2})$/);if(m)return new Date(2000+ +m[1],+m[2]-1,+m[3]);m=s.match(/^(\d{4})[-./](\d{1,2})[-./](\d{1,2})/);return m?new Date(+m[1],+m[2]-1,+m[3]):null};
async function weather(){try{const u=new URL('https://api.open-meteo.com/v1/forecast');u.searchParams.set('latitude',SEOUL.latitude);u.searchParams.set('longitude',SEOUL.longitude);u.searchParams.set('timezone','Asia/Seoul');u.searchParams.set('current','temperature_2m,apparent_temperature');u.searchParams.set('daily','temperature_2m_max,temperature_2m_min');u.searchParams.set('forecast_days','7');const r=await fetch(u,{cache:'no-store'});return r.ok?await r.json():null}catch{return null}}
async function mdRows(){try{const raw=process.env.GOOGLE_SERVICE_ACCOUNT_JSON;if(!raw)return[];const auth=new GoogleAuth({credentials:JSON.parse(raw),scopes:['https://www.googleapis.com/auth/spreadsheets.readonly']}),client=await auth.getClient(),token=await client.getAccessToken(),r=await fetch(`https://sheets.googleapis.com/v4/spreadsheets/${SHEET_ID}/values/${encodeURIComponent('MD!A1:Z3000')}`,{headers:{Authorization:`Bearer ${token.token||token}`},cache:'no-store'});if(!r.ok)return[];const a=(await r.json()).values||[];let hi=a.findIndex(row=>row.some(c=>norm(c).includes('업로드날짜'))&&row.some(c=>norm(c).includes('상품명')));if(hi<0)hi=0;const h=a[hi]||[],find=(...names)=>h.findIndex(x=>names.some(n=>norm(x).includes(norm(n)))),ix={date:find('업로드날짜'),product:find('상품명'),sale:find('판매가격'),margin:find('판매마진')};return a.slice(hi+1).map(r=>({date:ix.date>=0?txt(r[ix.date]):'',product:ix.product>=0?txt(r[ix.product]):'',sale:ix.sale>=0?num(r[ix.sale]):0,margin:ix.margin>=0?num(r[ix.margin]):0})).filter(x=>x.product||x.date)}catch{return[]}}
function category(name){const s=txt(name);for(const[k,words]of[['원피스',['원피스','드레스']],['상의',['가디건','니트','티셔츠','블라우스','셔츠','탑','나시','홀터넥']],['스커트',['스커트','치마']],['팬츠',['팬츠','바지','슬랙스','데님']],['아우터',['자켓','재킷','점퍼','코트','후드집업']],['세트',['세트','셋업']]])if(words.some(w=>s.includes(w)))return k;return'기타'}
const sig=(s,t)=>(s||[]).find(x=>x.title===t)?.products||[],uniq=a=>a.filter((x,i,z)=>z.findIndex(y=>(y.productNo||y.name)===(x.productNo||x.name))===i),chg=(n,p)=>p?Math.round((n-p)/p*100):null;
const shortName=s=>txt(s).length>38?txt(s).slice(0,38)+'…':txt(s),products=a=>a.length?a.slice(0,3).map(x=>`• ${shortName(x.name)}  |  7일 ${x.q7||0} · 30일 ${x.q30||0}${x.stock?` · 재고 ${x.stock}`:''}`).join('\n'):'• 해당 상품 없음';
export async function POST(req){try{const input=await req.json(),m=input.market||{},w=await weather(),all=await mdRows(),now=new Date(),d30=new Date(now);d30.setDate(d30.getDate()-29);const recent=all.filter(x=>{const d=parseDate(x.date);return d&&d>=d30&&d<=now}),cm={};recent.forEach(x=>cm[category(x.product)]=(cm[category(x.product)]||0)+1);const cats=Object.entries(cm).sort((a,b)=>b[1]-a[1]),hot=uniq([...sig(input.signals,'최근 반응 상승'),...sig(input.signals,'반응 지속'),...sig(input.signals,'신규 반응 감지')]),weak=uniq([...sig(input.signals,'반응 둔화'),...sig(input.signals,'반응 멈춤')]),d7=chg(m.q7,m.p7),d30v=chg(m.q30,m.p30),md30=chg(m.md30,m.mdPrev30);
const orderState=d7<0?'최근 주문 반응이 약해졌습니다.':d7>0?'최근 주문 반응이 좋아졌습니다.':'최근 주문 반응은 비슷합니다.';
const observation=`한눈에 보기\n\n${orderState}\n주문 7일  ${m.p7} → ${m.q7}개  ${d7===null?'':`(${d7<0?'▼':'▲'} ${Math.abs(d7)}%)`}\n주문 30일  ${m.p30} → ${m.q30}개  ${d30v===null?'':`(${d30v<0?'▼':'▲'} ${Math.abs(d30v)}%)`}\n업로드 30일  ${m.mdPrev30} → ${m.md30}개  ${md30===null?'':`(${md30<0?'▼':'▲'} ${Math.abs(md30)}%)`}\n\n핵심\n상품 등록은 늘었는데 주문은 줄었습니다. 지금은 등록 개수를 더 늘리기보다 최근 올린 상품이 실제 주문으로 이어졌는지 확인하는 게 우선입니다.${cats.length?`\n\nMD 구성  ${cats.slice(0,4).map(([k,v])=>`${k} ${v}`).join(' · ')}`:''}`;
const direction=`오늘 볼 것 ① 반응 상품\n${products(hot)}\n\n오늘 볼 것 ② 둔화 상품\n${products(weak)}\n\n오늘 할 일\n1. 반응 상품 3개의 공통점부터 확인\n2. 비슷한 신규 후보는 소규모 등록 테스트\n3. 주문이 다른 날짜에 반복된 상품만 재고 검토\n\n※ 주문 1건만으로는 재고 신호로 판단하지 않습니다.`;
const caution=`판단할 때 주의\n\n• 노출수·클릭수·전환율 데이터가 없어 주문 감소 원인을 상품 문제로 단정할 수 없습니다.\n• 다음 단계는 MD 신상품과 실제 주문을 상품번호로 연결하는 것입니다.\n• 연결 후에는 ‘올린 상품 중 몇 %가 주문을 만들었는지’를 직접 볼 수 있습니다.`;
const cur=w?.current||{},mx=(w?.daily?.temperature_2m_max||[]).slice(0,7),mn=(w?.daily?.temperature_2m_min||[]).slice(0,7),hi=mx.length?Math.max(...mx):null,lo=mn.length?Math.min(...mn):null;const weatherText=`서울 ${cur.temperature_2m??'-'}℃ · 체감 ${cur.apparent_temperature??'-'}℃${hi!=null&&lo!=null?`  |  7일 약 ${lo.toFixed(0)}~${hi.toFixed(0)}℃`:''}\n가을 상품 전환 타이밍을 보는 참고값으로만 사용합니다.`;return Response.json({observation,direction,caution,weather:weatherText,ai:false,source:'rule-based+md-sheet'})}catch(e){return Response.json({error:e.message||'OARS 분석 실패'},{status:500})}}
