'use client';
import {useEffect,useMemo,useState} from 'react';
const day=s=>{const d=new Date(`${s}T00:00:00`);return isNaN(d)?null:d};
const key=x=>x.productNo||`name:${x.product||'상품명 없음'}`;
const qty=(a,k,f,t)=>a.filter(x=>key(x)===k&&day(x.date)>=f&&day(x.date)<=t).reduce((s,x)=>s+(x.qty||1),0);
const days=(a,k,f,t)=>new Set(a.filter(x=>key(x)===k&&day(x.date)>=f&&day(x.date)<=t).map(x=>x.date)).size;
export default function ProductReaction(){const[data,setData]=useState(null),[loading,setLoading]=useState(true),[error,setError]=useState('');async function load(){setLoading(true);try{const r=await fetch('/api/dashboard-data',{cache:'no-store'}),j=await r.json();if(!r.ok)throw new Error(j.error||'불러오기 실패');setData(j);setError('')}catch(e){setError(e.message)}finally{setLoading(false)}}useEffect(()=>{load()},[]);const groups=useMemo(()=>{if(!data)return[];const now=new Date(),d7=new Date(now),d14=new Date(now),d30=new Date(now),p7s=new Date(now),p7e=new Date(now);d7.setDate(d7.getDate()-6);d14.setDate(d14.getDate()-13);d30.setDate(d30.getDate()-29);p7s.setDate(p7s.getDate()-13);p7e.setDate(p7e.getDate()-7);const m=new Map();for(const o of data.orders||[]){const k=key(o),r=m.get(k)||{key:k,productNo:o.productNo||'',name:o.product||'상품명 없음',after:0,returns:0};r.name=o.product||r.name;m.set(k,r)}for(const c of data.cancels||[]){const k=key(c),r=m.get(k)||{key:k,productNo:c.productNo||'',name:c.product||'상품명 없음',after:0,returns:0};if(c.type==='after')r.after+=(c.qty||1);if(c.type==='return')r.returns+=(c.qty||1);m.set(k,r)}const inv=new Map();for(const i of data.inventory||[]){const k=i.productNo||`name:${i.product}`,r=inv.get(k)||0;inv.set(k,r+(i.qty||0))}const rows=[...m.values()].map(r=>{const q7=qty(data.orders,r.key,d7,now),p7=qty(data.orders,r.key,p7s,p7e),q14=qty(data.orders,r.key,d14,now),q30=qty(data.orders,r.key,d30,now),active30=days(data.orders,r.key,d30,now),stock=inv.get(r.key)||0;return{...r,q7,p7,q14,q30,active30,stock}});return[
['🔥','최근 반응 상승','최근 7일 주문이 이전 7일보다 늘어난 상품',rows.filter(x=>x.q7>=2&&x.q7>x.p7),x=>`최근 7일 ${x.q7}개 · 이전 7일 ${x.p7}개 · 최근 30일 ${x.q30}개`],
['👀','신규 반응 감지','최근에 처음 반응이 잡히기 시작한 상품',rows.filter(x=>x.q7>=1&&x.q30<=2),x=>`최근 7일 ${x.q7}개 · 최근 30일 ${x.q30}개`],
['➡️','반응 지속','서로 다른 날짜에 주문이 이어지고 있는 상품',rows.filter(x=>x.q14>=2&&x.active30>=3),x=>`최근 14일 ${x.q14}개 · 최근 30일 주문 발생 ${x.active30}일`],
['📉','반응 둔화','최근 7일 주문이 이전 7일보다 줄어든 상품',rows.filter(x=>x.p7>=2&&x.q7<x.p7),x=>`이전 7일 ${x.p7}개 → 최근 7일 ${x.q7}개`],
['💤','반응 멈춤','최근 30일 주문은 있었지만 최근 7일 주문이 없는 상품',rows.filter(x=>x.q30>=2&&x.q7===0),x=>`최근 30일 ${x.q30}개 · 최근 7일 0개`],
['⚠️','재고 확인 필요','현재 보유 재고가 1~4개인 상품',rows.filter(x=>x.stock>0&&x.stock<5),x=>`현재 재고 ${x.stock}개 · 최근 7일 ${x.q7}개`],
['📦','발주 후 취소','발주 후 취소 기록이 있어 남는 재고를 확인할 상품',rows.filter(x=>x.after>0),x=>`발주 후 취소 ${x.after}개 · 현재 재고 ${x.stock}개`],
['🚨','배송 후 반품','배송 완료 후 반품 기록이 있는 상품',rows.filter(x=>x.returns>0),x=>`배송 후 반품 ${x.returns}개 · 최근 30일 주문 ${x.q30}개`]
]},[data]);const box={background:'#111315',border:'1px solid #34383d',borderRadius:18,padding:20};return <main style={{maxWidth:1000,margin:'auto',padding:'18px 18px 70px',fontFamily:'sans-serif',color:'#f4f4f5'}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'end',gap:12,flexWrap:'wrap'}}><div><h1 style={{margin:'8px 0'}}>상품 반응</h1><p style={{margin:0,color:'#a1a1aa'}}>주문·재고·취소·반품에서 감지된 상품별 움직임을 모아봅니다.</p></div><button onClick={load} disabled={loading}>{loading?'불러오는 중...':'새로고침'}</button></div>{error&&<section style={{...box,marginTop:18,color:'#fb7185'}}>{error}</section>}{!error&&loading&&<section style={{...box,marginTop:18,color:'#a1a1aa'}}>상품 반응을 계산하는 중...</section>}{!loading&&groups.map(([icon,title,desc,rows,detail])=><section key={title} style={{...box,marginTop:14}}><div style={{display:'flex',justifyContent:'space-between',gap:12,alignItems:'center'}}><div><h2 style={{margin:'0 0 5px',fontSize:19}}>{icon} {title}</h2><div style={{color:'#a1a1aa',fontSize:13}}>{desc}</div></div><b style={{fontSize:22}}>{rows.length}</b></div><div style={{marginTop:14,display:'grid',gap:8}}>{rows.length?rows.slice(0,20).map(x=><div key={x.key} style={{background:'#181a1c',borderRadius:12,padding:'12px 14px'}}><b style={{display:'block',lineHeight:1.45}}>{x.name}</b><span style={{display:'block',marginTop:5,color:'#a1a1aa',fontSize:13}}>{detail(x)}</span></div>):<div style={{color:'#71717a'}}>현재 해당 상품이 없습니다.</div>}</div></section>)}</main>}
