'use client';
import {useMemo,useState} from 'react';
import * as XLSX from 'xlsx';

const t=v=>String(v??'').trim();
const n=v=>{if(typeof v==='number')return Number.isFinite(v)?v:0;const x=Number(t(v).replace(/[^0-9.-]/g,''));return Number.isFinite(x)?x:0};
const won=v=>`${Math.round(v||0).toLocaleString('ko-KR')}원`;
const pct=(a,b)=>b?`${(a/b*100).toFixed(1)}%`:'0.0%';
const valid=v=>v!==null&&v!==undefined&&t(v)!==''&&t(v)!=='-';
const dateKey=v=>{if(v instanceof Date&&!isNaN(v))return `${v.getFullYear()}-${String(v.getMonth()+1).padStart(2,'0')}-${String(v.getDate()).padStart(2,'0')}`;const s=t(v);const m=s.match(/(20\d{2})[-./]?(\d{1,2})[-./]?(\d{1,2})/);return m?`${m[1]}-${m[2].padStart(2,'0')}-${m[3].padStart(2,'0')}`:''};
const monthOf=d=>d?.slice(0,7)||'';

function rowsOf(ws){return XLSX.utils.sheet_to_json(ws,{header:1,defval:'',raw:true}).slice(1).filter(r=>r.some(valid));}
function orderRow(r,kind='normal'){
  const off=kind==='normal'?0:8; // 취소반품 시트의 에이블리 원본 영역은 I열부터 시작
  const payDate=r[8+off], productOrder=r[9+off], product=r[12+off], price=n(r[13+off]), qty=n(r[16+off])||1, paid=n(r[19+off]);
  return {date:dateKey(payDate),productOrder:t(productOrder),product:t(product)||'(상품명 없음)',price,qty,paid:paid||price*qty};
}
function classifyCancel(r){
  const returnFee=n(r[2]);
  const hasReturnFlow=returnFee>0 && (valid(r[3])||valid(r[4])||valid(r[5]));
  if(hasReturnFlow)return 'return';
  const ordered=valid(r[6]) && t(r[6]).toLowerCase()!=='취소';
  return ordered?'after':'before';
}
function parseWorkbook(wb){
  const orderWs=wb.Sheets['에이블리 주문']; const cancelWs=wb.Sheets['취소 반품'];
  if(!orderWs)throw new Error("'에이블리 주문' 시트를 찾지 못했습니다.");
  const normal=rowsOf(orderWs).map(r=>orderRow(r,'normal')).filter(x=>x.date&&x.productOrder);
  const cancels=cancelWs?rowsOf(cancelWs).map(r=>({...orderRow(r,'cancel'),type:classifyCancel(r),reason:t(r[1]),returnFee:n(r[2])})).filter(x=>x.date&&x.productOrder):[];
  return {normal,cancels};
}
function Card({label,value,sub,tone}){return <div className={`kpi ${tone||''}`}><span>{label}</span><strong>{value}</strong><small>{sub}</small></div>}
function Bars({data}){const max=Math.max(1,...data.flatMap(x=>[x.gross,x.net,x.cancel]));return <div className="bars">{data.map(x=><div className="barGroup" key={x.key}><div className="barArea"><i title={`주문매출 ${won(x.gross)}`} style={{height:`${x.gross/max*100}%`}}/><i className="net" title={`실매출 ${won(x.net)}`} style={{height:`${x.net/max*100}%`}}/><i className="cancel" title={`취소·반품 ${won(x.cancel)}`} style={{height:`${x.cancel/max*100}%`}}/></div><b>{x.label}</b></div>)}</div>}
export default function Dashboard(){
 const [data,setData]=useState(null),[name,setName]=useState(''),[err,setErr]=useState(''),[month,setMonth]=useState('all');
 async function load(e){const f=e.target.files?.[0];if(!f)return;try{const wb=XLSX.read(await f.arrayBuffer(),{type:'array'});setData(parseWorkbook(wb));setName(f.name);setErr('');setMonth('all')}catch(x){setErr(x.message||'엑셀을 읽지 못했습니다.');setData(null)}}
 const vm=useMemo(()=>{if(!data)return null;const all=[...data.normal,...data.cancels];const months=[...new Set(all.map(x=>monthOf(x.date)).filter(Boolean))].sort();const inPeriod=x=>month==='all'||monthOf(x.date)===month;const normal=data.normal.filter(inPeriod),cancel=data.cancels.filter(inPeriod);const before=cancel.filter(x=>x.type==='before'),after=cancel.filter(x=>x.type==='after'),returns=cancel.filter(x=>x.type==='return');const gross=[...normal,...cancel].reduce((s,x)=>s+x.paid,0),deduct=cancel.reduce((s,x)=>s+x.paid,0),net=normal.reduce((s,x)=>s+x.paid,0);const byMonth=months.map(m=>{const no=data.normal.filter(x=>monthOf(x.date)===m),ca=data.cancels.filter(x=>monthOf(x.date)===m),g=[...no,...ca].reduce((s,x)=>s+x.paid,0),c=ca.reduce((s,x)=>s+x.paid,0);return{key:m,label:`${Number(m.slice(5))}월`,gross:g,cancel:c,net:g-c}});const productMap=new Map();for(const x of [...normal,...cancel]){const z=productMap.get(x.product)||{product:x.product,orders:0,cancel:0,qty:0,gross:0,net:0};z.orders++;z.qty+=x.qty;z.gross+=x.paid;if(cancel.includes(x))z.cancel++;else z.net+=x.paid;productMap.set(x.product,z)}const products=[...productMap.values()].sort((a,b)=>b.gross-a.gross);return{months,normal,cancel,before,after,returns,gross,deduct,net,byMonth,products}},[data,month]);
 return <main className="dash"><div className="top"><div><a href="/">← Ably Manager</a><h1>매출 대시보드</h1><p>주문 반응부터 취소·반품, 최종 실매출까지 한 번에 확인합니다.</p></div><label className="upload">주문시트 불러오기<input type="file" accept=".xlsx,.xls" onChange={load}/></label></div>{err&&<div className="error">{err}</div>}{!vm?<section className="empty"><h2>주문시트.xlsx를 올려주세요</h2><p>원본 파일은 브라우저에서 분석되며, 에이블리 주문 + 취소 반품 시트를 자동으로 구분합니다.</p><div className="rules"><b>현재 판정 규칙</b><span>발주 전 취소 · 발주일이 ‘취소’ 또는 발주정보 없음</span><span>발주 후 취소 · 실제 발주일/발주정보 존재</span><span>배송 후 반품 · 반품비용 + 회수/입고/처리 정보 존재</span></div></section>:<><div className="filter"><div><b>{name}</b><span> · {vm.normal.length+vm.cancel.length}건 분석</span></div><select value={month} onChange={e=>setMonth(e.target.value)}><option value="all">전체 기간</option>{vm.months.map(m=><option key={m} value={m}>{m.replace('-','년 ')}월</option>)}</select></div><section className="kpis"><Card label="총 주문매출" value={won(vm.gross)} sub={`전체 주문 ${vm.normal.length+vm.cancel.length}건`}/><Card label="최종 실매출" value={won(vm.net)} sub={`정상 판매 ${vm.normal.length}건`} tone="good"/><Card label="총 취소·반품" value={won(vm.deduct)} sub={`${vm.cancel.length}건 · ${pct(vm.deduct,vm.gross)}`} tone="bad"/><Card label="발주 후 취소" value={won(vm.after.reduce((s,x)=>s+x.paid,0))} sub={`${vm.after.length}건 · 재고 위험 확인`} tone="warn"/></section><section className="grid"><div className="panel wide"><div className="heading"><div><h2>월별 매출 흐름</h2><p>주문매출 / 실매출 / 취소·반품</p></div><div className="legend"><span>주문매출</span><span>실매출</span><span>취소·반품</span></div></div><Bars data={vm.byMonth}/></div><div className="panel"><h2>취소·반품 구조</h2><div className="break"><div><span>발주 전 취소</span><b>{vm.before.length}건</b><small>{won(vm.before.reduce((s,x)=>s+x.paid,0))}</small></div><div><span>발주 후 취소</span><b>{vm.after.length}건</b><small>{won(vm.after.reduce((s,x)=>s+x.paid,0))}</small></div><div><span>배송 후 반품</span><b>{vm.returns.length}건</b><small>{won(vm.returns.reduce((s,x)=>s+x.paid,0))}</small></div></div></div></section><section className="panel"><div className="heading"><div><h2>상품별 성과</h2><p>주문 반응과 최종 판매를 같이 봅니다.</p></div></div><div className="tableWrap"><table><thead><tr><th>상품</th><th>주문</th><th>취소·반품</th><th>수량</th><th>주문매출</th><th>실매출</th><th>취소율</th></tr></thead><tbody>{vm.products.slice(0,30).map(x=><tr key={x.product}><td>{x.product}</td><td>{x.orders}건</td><td>{x.cancel}건</td><td>{x.qty}</td><td>{won(x.gross)}</td><td><b>{won(x.net)}</b></td><td>{pct(x.cancel,x.orders)}</td></tr>)}</tbody></table></div></section><section className="panel"><h2>반품 사유</h2>{vm.returns.length?<div className="reasonList">{Object.entries(vm.returns.reduce((o,x)=>(o[x.reason||'사유 미기입']=(o[x.reason||'사유 미기입']||0)+1,o),{})).sort((a,b)=>b[1]-a[1]).map(([r,c])=><div key={r}><span>{r}</span><b>{c}건</b></div>)}</div>:<p className="muted">선택 기간에 배송 후 반품이 없습니다.</p>}</section></>}
 <style jsx>{`*{box-sizing:border-box}.dash{max-width:1240px;margin:auto;padding:32px 20px 80px;color:#171717}.top{display:flex;justify-content:space-between;gap:24px;align-items:flex-end}.top a{color:#777;text-decoration:none}.top h1{font-size:32px;margin:8px 0}.top p,.muted{color:#777;margin:0}.upload{background:#111;color:white;padding:13px 18px;border-radius:12px;font-weight:700;cursor:pointer}.upload input{display:none}.empty,.panel,.kpi,.filter{background:#fff;border:1px solid #e9e9e9;border-radius:18px}.empty{margin-top:24px;padding:52px;text-align:center}.rules{max-width:520px;margin:28px auto 0;display:grid;gap:9px;text-align:left;background:#f7f7f7;padding:20px;border-radius:14px}.filter{margin:24px 0 14px;padding:14px 18px;display:flex;justify-content:space-between;align-items:center}.filter span{color:#888}.filter select{padding:9px 12px;border:1px solid #ddd;border-radius:10px}.kpis{display:grid;grid-template-columns:repeat(4,1fr);gap:14px}.kpi{padding:20px}.kpi span{font-size:13px;color:#777}.kpi strong{display:block;font-size:24px;margin:9px 0}.kpi small{color:#888}.kpi.good{background:#f4fbf7}.kpi.bad{background:#fff6f6}.kpi.warn{background:#fff9ee}.grid{display:grid;grid-template-columns:2fr 1fr;gap:14px;margin-top:14px}.panel{padding:22px;margin-top:14px}.grid .panel{margin-top:0}.heading{display:flex;justify-content:space-between;align-items:flex-start}.heading h2,.panel h2{margin:0 0 6px;font-size:18px}.heading p{margin:0;color:#888;font-size:13px}.legend{display:flex;gap:14px;font-size:12px;color:#777}.bars{height:270px;display:flex;gap:14px;align-items:flex-end;padding-top:25px;overflow-x:auto}.barGroup{min-width:56px;flex:1;text-align:center}.barArea{height:215px;display:flex;align-items:flex-end;justify-content:center;gap:3px;border-bottom:1px solid #ddd}.barArea i{width:28%;min-height:2px;background:#bbb;border-radius:5px 5px 0 0}.barArea i.net{background:#222}.barArea i.cancel{background:#e6a4a4}.barGroup b{font-size:12px;color:#666}.break{display:grid;gap:10px;margin-top:18px}.break>div{padding:15px;background:#f7f7f7;border-radius:12px;display:grid;grid-template-columns:1fr auto;gap:4px}.break small{grid-column:1/3;color:#777}.tableWrap{overflow:auto;margin-top:16px}table{width:100%;border-collapse:collapse;min-width:850px}th,td{text-align:right;padding:13px 10px;border-bottom:1px solid #eee;font-size:13px}th:first-child,td:first-child{text-align:left;max-width:420px}.reasonList{display:grid;grid-template-columns:repeat(3,1fr);gap:10px;margin-top:16px}.reasonList div{display:flex;justify-content:space-between;padding:14px;background:#f7f7f7;border-radius:10px}.error{margin-top:18px;background:#fff1f1;padding:14px;border-radius:10px;color:#a33}@media(max-width:800px){.top{align-items:flex-start;flex-direction:column}.kpis{grid-template-columns:1fr 1fr}.grid{grid-template-columns:1fr}.empty{padding:30px 18px}.legend{display:none}.reasonList{grid-template-columns:1fr}.kpi strong{font-size:19px}}`}</style></main>
}